name: Java CI with Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package -DskipTests --file pom.xml

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Run App
        run: |
          JAR=$(ls target/*-SNAPSHOT.jar 2>/dev/null || ls target/*.jar | head -n1)
            nohup java -jar "$JAR" > app.log 2>&1 &
            for i in {1..60}; do
              if curl -fsS http://localhost:8080/actuator/health >/dev/null 2>&1 || \
                 curl -fsS http://localhost:8080/libros/inicio >/dev/null 2>&1; then
                echo "App is up"; break; fi
              echo "Waiting for app... ($i)"; sleep 2;
            done

      - name: Run Selenium UI Test
        env:
          BASE_URL: http://localhost:8080/libros/inicio
        run: mvn -B -Dtest=MvcDemoApplicationUITest test